/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import entities.Department;
import entities.Employee;
import entities.Project;
import java.util.Date;
import mycompany.Tools;

/**
 *
 * @author drmas
 */
public class frmTest extends javax.swing.JFrame {

    /**
     * Creates new form frmTest
     */
    public frmTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTestDepartment = new controllers.JMyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLTest = new javax.swing.JTable();
        btnTestEmployee = new controllers.JMyButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnEmployeePhone = new controllers.JMyButton();
        btnProject = new controllers.JMyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTestDepartment.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnTestDepartment.setText("Test Department");
        btnTestDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestDepartmentActionPerformed(evt);
            }
        });

        TBLTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(TBLTest);

        btnTestEmployee.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnTestEmployee.setText("Test Employee");
        btnTestEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestEmployeeActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEmployeePhone.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnEmployeePhone.setText("Test Employee Phone");
        btnEmployeePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeePhoneActionPerformed(evt);
            }
        });

        btnProject.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnProject.setText("Test Project");
        btnProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTestDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTestEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmployeePhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTestDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTestEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmployeePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProject, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTestDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestDepartmentActionPerformed
       Department dept = new Department();
      // dept.setDeptNo(2);
      // dept.setDeptName("IS");
      // dept.setLocation("Paris");
      // dept.add();
      //dept.update();
      //dept.delete();
     // dept.getAllRows(TBLTest);
     // Tools.msgBox(dept.getAutoNumber());
     //dept.getCustomRows("select * from department", TBLTest);
     //dept.getOneRow(TBLTest);
     //Tools.msgBox(dept.getValueByName("IS"));
     //Tools.msgBox(dept.getNameByValue("1"));
   
    }//GEN-LAST:event_btnTestDepartmentActionPerformed

    private void btnTestEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestEmployeeActionPerformed
     Employee emp = new Employee();
     //emp.setEmpNo(3);       
     /*emp.setEmpName("Ahmed Abdallah");
     emp.setAddress("Sudan");
     emp.setSalary(2000);
     emp.setHiringDate("2018/11/26");
     emp.setBirthDate("1990/05/04");
     emp.setDeptNo(1);
     emp.add();*/
    // emp.update();
    // emp.delete();    
    // emp.getAllRows(TBLTest);
    //Tools.msgBox(emp.getAutoNumber());
    // emp.getCustomRows("select * from employee_data", TBLTest);
    // emp.getOneRow(TBLTest);
    //Tools.msgBox(emp.getValueByName("Issam Drmas"));
    //Tools.msgBox(emp.getNameByValue("1"));
    
    }//GEN-LAST:event_btnTestEmployeeActionPerformed

    private void btnEmployeePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmployeePhoneActionPerformed

    private void btnProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjectActionPerformed
        Project proj = new Project();
        proj.setProjectNo(1);
       // proj.setProjectName("This is Work");
       // proj.setLocation("DM");
       // proj.setDeptNo(2);
       // proj.delete();
       // proj.getAllRows(TBLTest);
       //Tools.msgBox(proj.getAutoNumber());
        //proj.getCustomRows("select * from project", TBLTest);
        // proj.getAllRows(TBLTest);
          // Tools.msgBox(proj.getValueByName("Dress Will"));
        // Tools.msgBox(proj.getNameByValue("1"));
    }//GEN-LAST:event_btnProjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBLTest;
    private controllers.JMyButton btnEmployeePhone;
    private controllers.JMyButton btnProject;
    private controllers.JMyButton btnTestDepartment;
    private controllers.JMyButton btnTestEmployee;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
